# Generated by Django 4.1.13 on 2026-07-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_name', models.CharField(max_length=100)),
                ('crop_name', models.CharField(max_length=100)),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('modal_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('arrival_quantity', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('price_date', models.DateField()),
                ('source', models.CharField(default='AGMARKNET', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-price_date', 'market_name', 'crop_name'],
            },
        ),
        migrations.AddIndex(
            model_name='marketprice',
            index=models.Index(fields=['market_name'], name='market_pric_market__b77640_idx'),
        ),
        migrations.AddIndex(
            model_name='marketprice',
            index=models.Index(fields=['crop_name'], name='market_pric_crop_na_882577_idx'),
        ),
        migrations.AddIndex(
            model_name='marketprice',
            index=models.Index(fields=['price_date'], name='market_pric_price_d_4696d0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='marketprice',
            unique_together={('market_name', 'crop_name', 'price_date')},
        ),
    ]
