# Generated by Django 4.2.30 on 2026-07-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_prices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketprice',
            name='district_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='marketprice',
            index=models.Index(fields=['district_name'], name='market_pric_distric_22d9c6_idx'),
        ),
    ]
