# Generated by Django 4.2.30 on 2026-07-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_prices', '0002_marketprice_district_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='marketprice',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='marketprice',
            name='crop_name_gu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='marketprice',
            name='source',
            field=models.CharField(default='Official APMC', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='marketprice',
            unique_together={('market_name', 'crop_name', 'crop_name_gu', 'price_date')},
        ),
    ]
