# Generated by Django 4.2.30 on 2026-07-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgricultureExpert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('photo', models.CharField(blank=True, max_length=255, null=True)),
                ('qualification', models.CharField(max_length=255)),
                ('specialization', models.CharField(db_index=True, max_length=255)),
                ('experience', models.IntegerField(help_text='Experience in years')),
                ('district', models.CharField(db_index=True, max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('office_address', models.TextField()),
                ('languages', models.CharField(db_index=True, help_text='Comma separated languages', max_length=255)),
                ('availability', models.CharField(max_length=255)),
                ('google_map_link', models.URLField(blank=True, null=True)),
                ('rating', models.FloatField(default=5.0)),
            ],
            options={
                'verbose_name': 'Agriculture Expert',
                'verbose_name_plural': 'Agriculture Experts',
                'db_table': 'expert_agriculture_experts',
            },
        ),
    ]
