# Generated by Django 4.2.30 on 2026-07-18 19:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agricultureexpert',
            name='active_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='agricultureexpert',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agricultureexpert',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agricultureexpert',
            name='password',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='agricultureexpert',
            name='profile_photo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agricultureexpert',
            name='total_consultations',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='agricultureexpert',
            name='availability',
            field=models.CharField(default='Mon-Fri 9:00 AM - 5:00 PM', max_length=255),
        ),
        migrations.AlterField(
            model_name='agricultureexpert',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='agricultureexpert',
            name='languages',
            field=models.CharField(db_index=True, default='Gujarati, English', help_text='Comma separated languages', max_length=255),
        ),
        migrations.AlterField(
            model_name='agricultureexpert',
            name='office_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agricultureexpert',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
