# Generated by Django 4.2.30 on 2026-08-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0002_agricultureexpert_active_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agricultureexpert',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
    ]
