# Generated by Django 4.2.30 on 2026-07-18 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expert', '0002_agricultureexpert_active_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='consultations/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Replied', 'Replied'), ('Closed', 'Closed')], db_index=True, default='Pending', max_length=15)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_consultations', to='expert.agricultureexpert')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_consultations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'consultation',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('Farmer', 'Farmer'), ('Expert', 'Expert')], db_index=True, max_length=10)),
                ('message', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='consultation.consultation')),
            ],
            options={
                'db_table': 'consultation_reply',
                'ordering': ['created_date'],
            },
        ),
    ]
