# Generated by Django 4.2.30 on 2026-07-19 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
