# Generated by Django 4.2.30 on 2026-08-04 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0002_agricultureexpert_active_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consultation', '0002_consultation_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='Rating from 1 (worst) to 5 (best)')),
                ('review', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='consultation.consultation')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='expert.agricultureexpert')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expert Review',
                'verbose_name_plural': 'Expert Reviews',
                'db_table': 'expert_reviews',
            },
        ),
    ]
