# Generated by Django 4.2.30 on 2026-08-05 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='purpose',
            field=models.CharField(choices=[('registration', 'Registration'), ('forgot_password', 'Forgot Password')], default='forgot_password', max_length=20),
        ),
        migrations.AddField(
            model_name='otp',
            name='reset_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='otp',
            name='reset_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
