# Generated by Django 4.2.30 on 2026-07-08 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(max_length=255, verbose_name='Farm Name')),
                ('village', models.CharField(max_length=255, verbose_name='Village')),
                ('taluka', models.CharField(max_length=255, verbose_name='Taluka')),
                ('district', models.CharField(max_length=255, verbose_name='District')),
                ('state', models.CharField(default='Gujarat', max_length=255, verbose_name='State')),
                ('total_area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Area')),
                ('area_unit', models.CharField(choices=[('Acre', 'Acre'), ('Hectare', 'Hectare')], max_length=20, verbose_name='Area Unit')),
                ('soil_type', models.CharField(max_length=100, verbose_name='Soil Type')),
                ('irrigation_type', models.CharField(max_length=100, verbose_name='Irrigation Type')),
                ('latitude', models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True, verbose_name='Longitude')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to=settings.AUTH_USER_MODEL, verbose_name='Farmer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
