# Generated by Django 4.2.30 on 2026-07-08 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=255, verbose_name='Crop Name')),
                ('crop_variety', models.CharField(max_length=255, verbose_name='Crop Variety')),
                ('season', models.CharField(choices=[('Kharif', 'Kharif'), ('Rabi', 'Rabi'), ('Summer', 'Summer')], max_length=20, verbose_name='Season')),
                ('sowing_date', models.DateField(verbose_name='Sowing Date')),
                ('expected_harvest_date', models.DateField(verbose_name='Expected Harvest Date')),
                ('harvest_date', models.DateField(blank=True, null=True, verbose_name='Harvest Date')),
                ('area_used', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Area Used')),
                ('area_unit', models.CharField(choices=[('Acre', 'Acre'), ('Hectare', 'Hectare')], max_length=20, verbose_name='Area Unit')),
                ('expected_yield', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Expected Yield (kg)')),
                ('actual_yield', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Actual Yield (kg)')),
                ('seed_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Seed Cost')),
                ('fertilizer_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Fertilizer Cost')),
                ('pesticide_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Pesticide Cost')),
                ('labour_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Labour Cost')),
                ('other_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Other Cost')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Cost')),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Selling Price (per kg)')),
                ('sold_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Sold Quantity (kg)')),
                ('crop_image', models.ImageField(blank=True, null=True, upload_to='crops/', verbose_name='Crop Image')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('crop_status', models.CharField(choices=[('Sown', 'Sown'), ('Growing', 'Growing'), ('Harvested', 'Harvested'), ('Sold', 'Sold')], default='Sown', max_length=30, verbose_name='Crop Status')),
                ('disease_status', models.CharField(choices=[('Healthy', 'Healthy'), ('Healthy (Low Risk)', 'Healthy (Low Risk)'), ('Monitored', 'Monitored'), ('Diseased', 'Diseased')], default='Healthy', max_length=50, verbose_name='Disease Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='farmer.farm', verbose_name='Farm')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
