# Generated by Django 4.1.13 on 2026-07-08 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0002_crop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_yard', models.CharField(max_length=255, verbose_name='Market Yard')),
                ('sale_date', models.DateField(verbose_name='Sale Date')),
                ('sold_quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Sold Quantity (kg)')),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Price Per KG')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Revenue')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='farmer.crop', verbose_name='Crop')),
            ],
            options={
                'ordering': ['-sale_date'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('Seed', 'Seed'), ('Fertilizer', 'Fertilizer'), ('Pesticide', 'Pesticide'), ('Labour', 'Labour'), ('Irrigation', 'Irrigation'), ('Machinery', 'Machinery'), ('Transportation', 'Transportation'), ('Other', 'Other')], max_length=50, verbose_name='Expense Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('expense_date', models.DateField(verbose_name='Expense Date')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='farmer.crop', verbose_name='Crop')),
            ],
            options={
                'ordering': ['-expense_date'],
            },
        ),
    ]
