# Generated by Django 4.2.30 on 2026-07-19 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CropRecommendationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('district', models.CharField(max_length=100, verbose_name='District')),
                ('soil_type', models.CharField(max_length=100, verbose_name='Soil Type')),
                ('season', models.CharField(max_length=50, verbose_name='Season')),
                ('rainfall', models.FloatField(default=0.0, verbose_name='Rainfall (mm)')),
                ('recommended_crop', models.CharField(max_length=100, verbose_name='Recommended Crop')),
                ('confidence', models.FloatField(verbose_name='Confidence (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crop_recommendations', to=settings.AUTH_USER_MODEL, verbose_name='Farmer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
