# Generated by Django 4.2.30 on 2026-07-19 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='Temperature (°C)')),
                ('condition', models.CharField(blank=True, max_length=100, null=True, verbose_name='Condition')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weather_requests', to=settings.AUTH_USER_MODEL, verbose_name='Farmer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
