# Generated by Django 4.2.30 on 2026-07-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('gujarati_name', models.CharField(max_length=255)),
                ('scheme_type', models.CharField(choices=[('Central', 'Central'), ('Gujarat', 'Gujarat')], db_index=True, max_length=50)),
                ('description', models.TextField()),
                ('eligibility', models.TextField()),
                ('benefits', models.TextField()),
                ('required_documents', models.TextField(blank=True, null=True)),
                ('official_website', models.URLField(blank=True, max_length=500, null=True)),
                ('apply_link', models.URLField(blank=True, max_length=500, null=True)),
                ('farmer_category', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('crop_category', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], db_index=True, default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['scheme_name'],
            },
        ),
    ]
