# Generated by Django 4.2.30 on 2026-07-19 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('government_schemes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='governmentscheme',
            options={'ordering': ['-featured', 'scheme_name']},
        ),
        migrations.AddField(
            model_name='governmentscheme',
            name='category',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='governmentscheme',
            name='department',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='governmentscheme',
            name='district',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='governmentscheme',
            name='end_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='governmentscheme',
            name='featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='governmentscheme',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='governmentscheme',
            name='start_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='governmentscheme',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='governmentscheme',
            name='gujarati_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='governmentscheme',
            name='scheme_type',
            field=models.CharField(choices=[('Central', 'Central'), ('Gujarat', 'Gujarat')], db_index=True, default='Central', max_length=50),
        ),
        migrations.AlterField(
            model_name='governmentscheme',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Expired', 'Expired')], db_index=True, default='Active', max_length=20),
        ),
    ]
