# Generated by Django 4.1.13 on 2026-07-09 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmer', '0003_sales_expense'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=100, verbose_name='Crop')),
                ('image', models.ImageField(upload_to='diseases/', verbose_name='Crop Leaf Image')),
                ('prediction', models.CharField(max_length=255, verbose_name='Prediction')),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Confidence (%)')),
                ('status', models.CharField(choices=[('Healthy', 'Healthy'), ('Diseased', 'Diseased')], default='Healthy', max_length=20, verbose_name='Status')),
                ('treatment', models.TextField(blank=True, verbose_name='Treatment')),
                ('prevention', models.TextField(blank=True, verbose_name='Prevention')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disease_detections', to='farmer.farm', verbose_name='Farm')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_detections', to=settings.AUTH_USER_MODEL, verbose_name='Farmer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
